### ISSUE TITLE
Failed Ajax request or invalid JSON returned for Cover Image

### ISSUE THREAD

**Issue by marlara** [pkp/quickSubmit#64] opened 2022-12-21 14:22 UTC
OJS Version: 3.3.0.13
PHP version : 8.0.26
Apache version: Apache/2.4.54 (Ubuntu)

In the apache log I have 

`PHP Fatal error:  Declaration of UploadImageForm::execute($request) must be compatible with Form::execute(...$functionArgs) in /var/www/ojs/plugins/importexport/quickSubmit/classes/form/UploadImageForm.inc.php on line 145`

**Comment by asmecher** [comment] 2023-01-03 19:49
@marlara, this is a duplicate of https://github.com/pkp/quickSubmit/issues/61, which has already been resolved.

**Closed by asmecher** 2023-01-03 19:49 UTC
