### ISSUE TITLE
Latest release is behind current branch

### ISSUE THREAD

**Issue by SorinCR** [pkp/quickSubmit#67] opened 2023-02-02 19:00 UTC
Installed this plugin trough the plugin gallery and I encountered this error

> Declaration of UploadImageForm::execute($request) must be compatible with Form::execute(...$functionArgs) in /var/www/html/colindancias/plugins/importexport/quickSubmit/classes/form/UploadImageForm.inc.php on line 145

PHP 8.1

Took me a good while to fix it by replacing line 145 with the following:
```
	function execute(...$functionArgs) {
		$request = Application::get()->getRequest();
                ...
```
Just to see that the current code from this repo has that covered already.
Please make a new release for the current php version, thanks :)
Also, great plugin 👍

**Comment by asmecher** [comment] 2023-02-03 23:30
This is a duplicate of https://github.com/pkp/quickSubmit/issues/61; I've released v1.0.6-1 of the plugin to the plugin gallery.

**Closed by asmecher** 2023-02-03 23:30 UTC
